---
# vars file for homebrew
homebrew_enabled_repositories:
  - hashicorp/tap

homebrew_installed_packages:
  - ansible
  - cask
  - wget
  - git
  - mas
  - ca-certificates
  - cfssl
  - kind
  - kubernetes-cli
  - minikube
  - python
  - pyenv
  - go
  - awscli
  - azure-cli
  - hashicorp/tap/terraform
  - tfenv
  - kubebuilder
  - kustomize
  - helm
  - npm
  - hugo
